<a href="https://colab.research.google.com/github/KLeeDE/Python/blob/master/2_Python_Important_Python_Modules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**GEOG473-673 Python Week2**

Class : GEOG673 Select Technical Topics 

Topic : Important Python Modules

Writer : Kyungmin Lee / @KLeeDE

Date : Nov 25, 2020

#Tutorial

https://github.com/jsimkins2/geog473-673/blob/master/Python/Introduction_to_Numpy.ipynb

#NumPy

NumPy is the fundamental package for scientific computing with Python. It is short for numerical python.

It contains among other things:

* a powerful N-dimensional array object
* mathematical functions which operate on these arrays
* useful linear algebra, Fourier transform, and random number capabilities



In [1]:
import numpy as np   # standard import abbreviation

In [2]:
a = np.array([1, 2, 3])  # a NumPy array of three integers
a

array([1, 2, 3])

In [3]:
a.shape  # tuple representing the size of each dimension

(3,)

In [4]:
a.ndim  # number of dimensions

1

In [5]:
a.dtype  # Data type information

dtype('int64')

In [6]:
b = np.array([1., 2., 3., 4.])  # a NumPy array of four floats

In [7]:
b.shape

(4,)

In [9]:
b.dtype

dtype('float64')

In [10]:
a = np.arange(10)  # a range of values from (0) to 10
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
a = np.arange(1, 10, 2, dtype='float32')
print(a)
print(a.dtype)

[1. 3. 5. 7. 9.]
float32


In [12]:
a = np.linspace(0, 10, 5)  # 5 linearly spaced entries from 0 to 10 
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [13]:
# Convert degrees to radians
np.radians(90)

1.5707963267948966

In [14]:
# Conver radians to degrees
np.degrees(1.5707963267948966)

90.0

In [15]:
# Special "not a number" value
np.nan

nan

##Exercise

1) Convert the following degree list to radians using a for loop.

deg_list = [15,36,45,88,90]

rad_list = ?


###Array operations

In [21]:
a = np.array([1, 2, 3])
b = np.array([6, 7, 8])
a + b

array([ 7,  9, 11])

In [22]:
print(a+b)

[ 7  9 11]


In [17]:
a * b

array([ 6, 14, 24])

In [23]:
a = [1, 2, 3]
b = [6, 7, 8]

a + b

[1, 2, 3, 6, 7, 8]

In [24]:
print(a+b)

[1, 2, 3, 6, 7, 8]


In [25]:
a * b

TypeError: ignored

In [26]:
# -- if we want to add lists the same way we just did with arrays, here is how you would do that
c = [i+j for i, j in zip(a, b)]
print(c)

[7, 9, 11]


In [27]:
a = np.linspace(-np.pi, np.pi, 10)# Return evenly spaced numbers over a specified interval.
a

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [28]:
np.sin(a)

array([-1.22464680e-16, -6.42787610e-01, -9.84807753e-01, -8.66025404e-01,
       -3.42020143e-01,  3.42020143e-01,  8.66025404e-01,  9.84807753e-01,
        6.42787610e-01,  1.22464680e-16])

In [29]:
np.cos(a)

array([-1.        , -0.76604444, -0.17364818,  0.5       ,  0.93969262,
        0.93969262,  0.5       , -0.17364818, -0.76604444, -1.        ])

## Multiple dimensions

In [30]:
a = np.arange(12).reshape(3, 4)  # create a 2 dimensional array with dimensions of 3 and 4
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [31]:
a.ndim # find the number of dimensions of array a

2

In [32]:
a.shape # find the shape of array a

(3, 4)

In [33]:
2 * a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

##Indexing and Slicing

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a = np.arange(10)
a[3]

3

In [35]:
a[2:-2]

array([2, 3, 4, 5, 6, 7])

In [37]:
a[1::2]

array([1, 3, 5, 7, 9])

In [38]:
b = np.arange(12).reshape(3, 4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
b[1, 2]

6

In [40]:
b[2]  # select the entire second dimension

array([ 8,  9, 10, 11])

In [41]:
b[1:3, :3]  # slices are also allowed

array([[ 4,  5,  6],
       [ 8,  9, 10]])

In [42]:
b[:, 2]  # all elements in the first dimension

array([ 2,  6, 10])

In [43]:
# ... (ellipsis) will replace one or more dimensions
b[..., 2]

array([ 2,  6, 10])

#**Exercises**
2) Create a null vector (1-d array) of size 10

3) Create a null vector (1-d array) of size 10 but with the fifth value being 1

4) Create a vector with values ranging from 10 to 49

5) Reverse a vector (first element becomes the last)

##Logical Indexing

In [44]:
a = np.arange(5)

In [45]:
selection = np.array([True, False, False, True, True])
a[selection]

array([0, 3, 4])

In [46]:
a[a>2]

array([3, 4])

##Masked arrays


Masked arrays are a specialization of NumPy arrays to handle flagging elements that should be ignored. This allows for the elimination of values from computations.

This is great for ignoring bad values but keeping the shape of the array you want.



In [47]:

a = np.ma.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
a[2,2] = np.ma.masked
print(a)

[[0 1 2 3]
 [4 5 6 7]
 [8 9 -- 11]]


In [49]:
b = a * 2
print(b)

[[0 2 4 6]
 [8 10 12 14]
 [16 18 -- 22]]


In [50]:
# logical masking
a[a > 6] = np.ma.masked
print(a)

[[0 1 2 3]
 [4 5 6 --]
 [-- -- -- --]]


In [51]:
# unmasked an element
a[-1, -1] = 42
print(a)

[[0 1 2 3]
 [4 5 6 --]
 [-- -- -- 42]]


#**Exercises**

6) Create a 3x3 matrix with values ranging from 0 to 8. Multiply by 2.

7) Mask the all values less than 3 in the matrix formed above.

8) Given the list of l=[-.7, -1.5, 14, 0.3, 1, 1.8, 5] , convert to array and mask all values greater than 1.